// Original print-oriented vector master sheets. No raster tracing or runtime AI.
import C from 'clipper-lib';
import fs from 'node:fs';
const S=1000;
const V=(x,y)=>({X:x,Y:y});
const polar=(r,a)=>V(r*Math.cos(a),r*Math.sin(a));
function bezier(a,b,c,d,n=18){return Array.from({length:n+1},(_,i)=>{let t=i/n,u=1-t;return V(u*u*u*a.X+3*u*u*t*b.X+3*u*t*t*c.X+t*t*t*d.X,u*u*u*a.Y+3*u*u*t*b.Y+3*u*t*t*c.Y+t*t*t*d.Y);});}
const circle=(r,n=40)=>Array.from({length:n},(_,i)=>polar(r,i*Math.PI*2/n));
function stroke(points,width=.65,closed=false){const co=new C.ClipperOffset(2,40),out=[];co.AddPath(points.map(v=>V(Math.round(v.X*S),Math.round(v.Y*S))),C.JoinType.jtRound,closed?C.EndType.etClosedLine:C.EndType.etOpenRound);co.Execute(out,width*S/2);return out;}
function normalize(paths){const c=new C.Clipper();c.StrictlySimple=true;c.AddPaths(paths,C.PolyType.ptSubject,true);const out=[];c.Execute(C.ClipType.ctUnion,out,C.PolyFillType.pftNonZero,C.PolyFillType.pftNonZero);return C.Clipper.CleanPolygons(out,12);}
const move=(paths,x,y,angle=0,scale=1)=>{const c=Math.cos(angle),s=Math.sin(angle);return paths.map(r=>r.map(p=>V(Math.round((p.X*c-p.Y*s)*scale+x*S),Math.round((p.X*s+p.Y*c)*scale+y*S))));};
function petal(length,width){return [...bezier(V(0,0),V(length*.35,-width),V(length*.9,-width*.65),V(length,0),12),...bezier(V(length,0),V(length*.9,width*.65),V(length*.35,width),V(0,0),12).slice(1)];}
function rosette(r=16){let paths=[...stroke(circle(3.3),.75,true),...stroke(circle(r*.65),.65,true)];for(let i=0;i<12;i++){const a=i*Math.PI/6;paths.push(...move(stroke(petal(r-2,3.4),.65,true),...Object.values(polar(3,a)),a));}for(let i=0;i<24;i++){let a=i*Math.PI/12;paths.push(...move(stroke(circle(1.0,12),.55,true),...Object.values(polar(r+1.8,a))));}return normalize(paths);}
function curl(){let p=[...bezier(V(0,0),V(16,-16),V(31,-10),V(29,2)),...bezier(V(29,2),V(25,18),V(8,11),V(15,2)).slice(1),...bezier(V(15,2),V(19,-3),V(25,1),V(20,5)).slice(1)];let out=stroke(p,.9);for(let i=0;i<5;i++){let t=.15+i*.14;const v=p[Math.floor(t*(p.length-1))];out.push(...move(stroke(petal(7,2.1),.65,true),v.X,v.Y,-1.4+i*.35));}return normalize(out);}
function paisley(){const p=[...bezier(V(0,-18),V(17,-7),V(17,16),V(1,18)),...bezier(V(1,18),V(-17,18),V(-17,-6),V(-3,-6)).slice(1),...bezier(V(-3,-6),V(5,-5),V(5,-13),V(0,-18)).slice(1)];let out=stroke(p,.85,true);out.push(...move(stroke(p,.6,true),0,2,0,.7));for(let i=0;i<8;i++){const a=i*Math.PI/4;out.push(...move(stroke(petal(7,1.8),.55,true),0,7,a));}return normalize(out);}
function viennaTile(){let p=rosette(15);for(let i=0;i<4;i++){const a=i*Math.PI/2;p.push(...move(curl(),19*Math.cos(a),19*Math.sin(a),a+Math.PI/4,.64));p.push(...move(paisley(),35*Math.cos(a+.78),35*Math.sin(a+.78),a+2.25,.82));}return normalize(p);}
function rose(){let p=[];for(let ring=0;ring<4;ring++){const n=ring+3,r=3+ring*3.3;for(let j=0;j<n;j++){const a=j*Math.PI*2/n+ring*.8,pts=bezier(polar(r*.6,a-.55),polar(r+2,a-.8),polar(r+3,a+.6),polar(r*.68,a+.95),24);p.push(...stroke(pts,.85));}}p.push(...stroke(circle(1.2,16),.75,true));return normalize(p);}
function roseTile(){let p=rose();for(let i=0;i<4;i++){const a=i*Math.PI/2;const stem=bezier(V(11,6),V(25,12),V(13,35),V(35,37));let branch=stroke(stem,.85);for(let j=0;j<4;j++){const pt=stem[3+j*4];branch.push(...move(stroke(petal(11,4),.75,true),pt.X,pt.Y,(j%2?2.2:-.55)));const mid=bezier(V(0,0),V(3,0),V(8,0),V(10,0),5);branch.push(...move(stroke(mid,.55),pt.X,pt.Y,(j%2?2.2:-.55)));}p.push(...move(branch,0,0,a));p.push(...move(rose(),32*Math.cos(a+.3),32*Math.sin(a+.3),a,.45));}return normalize(p);}
function feather(){let p=[];const stem=bezier(V(0,36),V(-7,10),V(0,-15),V(2,-31),32);p.push(...stroke(stem,1));const eye=[...bezier(V(1,-32),V(21,-19),V(14,2),V(0,4)),...bezier(V(0,4),V(-17,0),V(-20,-20),V(1,-32)).slice(1)];p.push(...stroke(eye,.8,true),...move(stroke(eye,.65,true),0,-5,0,.65),...move(stroke(circle(3.5,24),.7,true),0,-13));for(let k=0;k<11;k++){const y=3+k*2.7,reach=11+(10-k)*.9;for(const side of [-1,1])p.push(...stroke(bezier(V(-2,y+3),V(side*reach*.6,y-6),V(side*reach,y-10),V(side*(reach+2),y-19),16),.6));}return normalize(p);}
const definitions=[{id:'vienna',name:'Венское кружево',description:'Розетки, пейсли и тонкая ажурная сетка',category:'Кружево',minFeature:.55,tile:viennaTile,step:94},{id:'rose-garden',name:'Садовые розы',description:'Раскрытые розы и переплетённые ветви',category:'Флористика',minFeature:.55,tile:roseTile,step:94},{id:'peacock',name:'Павлинье перо',description:'Крупные перья с резными прожилками',category:'Перья',minFeature:.6,tile:feather,step:66}];
const assets=[];
for(const d of definitions){let p=[],tile=d.tile();for(let y=-2;y<=2;y++)for(let x=-2;x<=2;x++){let xx=x*d.step,yy=y*d.step;if(d.id==='peacock')xx+=(y%2)*d.step*.5;p.push(...move(tile,xx,yy,d.id==='peacock'?(x%2?-.35:.35):0));}
 // Fine diamond net joins motifs into a whole textile-like drawing.
 const motifs=normalize(p); const net=[];
 const limit=200,spacing=d.id==='vienna'?10:18,width=d.id==='vienna'?.55:.6;
 for(let b=-400;b<=400;b+=spacing){for(const slope of [-1,1]){const candidates=[V(-limit,slope*-limit+b),V(limit,slope*limit+b),V((-limit-b)/slope,-limit),V((limit-b)/slope,limit)].filter(v=>Math.abs(v.X)<=limit+.001&&Math.abs(v.Y)<=limit+.001);if(candidates.length>=2){const a=candidates[0],z=candidates.find(v=>Math.hypot(v.X-a.X,v.Y-a.Y)>1);if(z)net.push(...stroke([a,z],width));}}}
 const co=new C.ClipperOffset(2,40),mask=[];co.AddPaths(motifs,C.JoinType.jtRound,C.EndType.etClosedPolygon);co.Execute(mask,1100);
 const cut=new C.Clipper();cut.AddPaths(net,C.PolyType.ptSubject,true);cut.AddPaths(mask,C.PolyType.ptClip,true);const grid=[];cut.Execute(C.ClipType.ctDifference,grid,C.PolyFillType.pftNonZero,C.PolyFillType.pftNonZero);
 p=normalize([...motifs,...grid]);const paths=p.map(r=>r.map(v=>V(v.X/S,v.Y/S)));const asset={id:d.id,name:d.name,category:d.category,description:d.description,tags:[d.category,'готовое полотно','ажур'],viewBox:[-200,-200,400,400],paths,preview:'/designs/'+d.id+'.svg',license:'CC0-1.0; original procedural vector lace',revision:1,minFeature:d.minFeature};assets.push(asset);
 const path=paths.map(r=>r.map((v,i)=>(i?'L':'M')+v.X+','+v.Y).join('')+'Z').join('');fs.writeFileSync('public/designs/'+d.id+'.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-110 -110 220 220"><rect x="-210" y="-210" width="420" height="420" fill="#544d50"/><path fill="#fff7e8" fill-rule="nonzero" d="${path}"/></svg>`);console.log(d.id,paths.length,'rings',paths.reduce((s,p)=>s+p.length,0),'vertices');}
fs.writeFileSync('src/library/designs.json',JSON.stringify(assets));
